version: "3.7"

services:
    php:
        volumes:
            - .:/opt/app
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ~/phpstan-pro:/tmp/phpstan-fixer
        ports:
            - "11111:11111"
